import { makeStyles } from "@material-ui/core/styles";
import { isAbsolute } from "path";

const useStyles = makeStyles({
  footer: { width: "1731px", height: "431px", position: "absolute" },
  rectangle6: { backgroundColor: "#363636", height: "364px", width: "1730px" },
  rectangle12: { backgroundColor: "#1a1a1a", height: "67px", width: "1728px" },
  loremipsum: {
    color: "#ffffff",
    textAlign: "left",
    verticalAlign: "text-top",
    fontSize: "14px",
    fontFamily: "Inter",
    lineHeight: "auto",
    borderStyle: "hidden",
    outline: "none",
    left: "380px",
    top: "143px",
    position: "absolute",
    width: "98px",
  },
  loremipsum2: {
    color: "#ffffff",
    textAlign: "left",
    verticalAlign: "text-top",
    fontSize: "14px",
    fontFamily: "Inter",
    left: "1270px",
    top: "3670px",
    width: "98px",
    height: "17px",
    position: "absolute",
    lineHeight: "auto",
    borderStyle: "hidden",
    outline: "none",
  },
  issimplydummytextoftheprintingandtypesettingindustry: {
    color: "#ffffff",
    textAlign: "center",
    verticalAlign: "text-top",
    fontSize: "11px",
    fontFamily: "Inter",
    left: "717px",
    top: "3904px",
    width: "319px",
    height: "13px",
    position: "absolute",
    lineHeight: "auto",
    borderStyle: "hidden",
    outline: "none",
  },
  issimplydummytextoftheprintingandtypesettingindustry_2: {
    color: "#ffffff",
    textAlign: "center",
    verticalAlign: "text-top",
    fontSize: "10px",
    fontFamily: "Inter",
    left: "733px",
    top: "3920px",
    width: "286px",
    height: "12px",
    position: "absolute",
    lineHeight: "auto",
    borderStyle: "hidden",
    outline: "none",
  },
  line62: {
    width: "196px",
    transform: "rotate(-91deg)",
    border: "1px solid #222222",
    top: "3619px",
    left: "660px",
    position: "absolute",
  },
  line63: {
    width: "196px",
    transform: "rotate(-91deg)",
    border: "1px solid #222222",
    top: "3616px",
    left: "1109px",
    position: "absolute",
  },
  ofapagewhenlookingatitslayout_thepointofusingloremipsumisthatithasamore_or_lessnormaldistribution: {
    color: "#ffffff",
    textAlign: "center",
    verticalAlign: "text-top",
    fontSize: "14px",
    fontFamily: "Inter",
    left: "275px",
    top: "3703px",
    width: "333px",
    height: "51px",
    position: "absolute",
    lineHeight: "auto",
    borderStyle: "hidden",
    outline: "none",
  },
  loremipsum4: {
    color: "#ffffff",
    textAlign: "left",
    verticalAlign: "text-top",
    fontSize: "14px",
    fontFamily: "Inter",
    left: "836px",
    top: "3667px",
    width: "98px",
    height: "17px",
    position: "absolute",
    lineHeight: "auto",
    borderStyle: "hidden",
    outline: "none",
  },
  ofapagewhenlookingatitslayout_thepointofusingloremipsumisthatithasamore_or_lessnormaldistribution2: {
    color: "#ffffff",
    textAlign: "center",
    verticalAlign: "text-top",
    fontSize: "14px",
    fontFamily: "Inter",
    left: "718px",
    top: "3700px",
    width: "333px",
    height: "51px",
    position: "absolute",
    lineHeight: "auto",
    borderStyle: "hidden",
    outline: "none",
  },
  ofapagewhenlookingatitslayout_thepointofusingloremipsumisthatithasamore_or_lessnormaldistribution3: {
    color: "#ffffff",
    textAlign: "center",
    verticalAlign: "text-top",
    fontSize: "14px",
    fontFamily: "Inter",
    left: "1161px",
    top: "3703px",
    width: "333px",
    height: "51px",
    position: "absolute",
    lineHeight: "auto",
    borderStyle: "hidden",
    outline: "none",
  },
});

export { useStyles };
